import "./App.css";
import UsersGrid from "./components/UsersGrid";

const USERS = [
    {
        id: "6891dafc3419eb7aec1a1ee0",
        firstName: "Lynne",
        lastName: "Hurley",
        gender: "female",
        phone: "+1 (935) 443-3147",
        company: "ECRATIC",
        email: "lynnehurley@ecratic.com",
    },
    {
        id: "6891dafc4ef72495aff6eebe",
        firstName: "Talley",
        lastName: "Acosta",
        gender: "male",
        phone: "+1 (897) 471-3117",
        company: "GEEKWAGON",
        email: "talleyacosta@geekwagon.com",
    },
    {
        id: "6891dafce4fc282ef885b9db",
        firstName: "Rosalie",
        lastName: "Guzman",
        gender: "female",
        phone: "+1 (944) 452-2093",
        company: "GEEKOLOGY",
        email: "rosalieguzman@geekology.com",
    },
    {
        id: "6891dafc9365e58c65b7097f",
        firstName: "Terri",
        lastName: "Gould",
        gender: "female",
        phone: "+1 (830) 446-2507",
        company: "MELBACOR",
        email: "terrigould@melbacor.com",
    },
    {
        id: "6891dafc2d55ef6443875efe",
        firstName: "Barlow",
        lastName: "Bender",
        gender: "male",
        phone: "+1 (854) 474-2388",
        company: "ZYTREK",
        email: "barlowbender@zytrek.com",
    },
    {
        id: "6891dafc3d4bf062d5d8a07e",
        firstName: "Pam",
        lastName: "Burns",
        gender: "female",
        phone: "+1 (887) 517-2948",
        company: "RAMEON",
        email: "pamburns@rameon.com",
    },
    {
        id: "6891dafc8f40768d829d97e3",
        firstName: "Mathews",
        lastName: "Sloan",
        gender: "male",
        phone: "+1 (883) 589-2767",
        company: "PLASMOX",
        email: "mathewssloan@plasmox.com",
    },
    {
        id: "6891dafce39b10eabca24954",
        firstName: "Jeanie",
        lastName: "Sanders",
        gender: "female",
        phone: "+1 (993) 408-2160",
        company: "ORONOKO",
        email: "jeaniesanders@oronoko.com",
    },
    {
        id: "6891dafcade014e48e4cbb9b",
        firstName: "Kate",
        lastName: "Molina",
        gender: "female",
        phone: "+1 (902) 580-2710",
        company: "APEXIA",
        email: "katemolina@apexia.com",
    },
    {
        id: "6891dafcde1f9376c1e03e30",
        firstName: "Mason",
        lastName: "Barry",
        gender: "male",
        phone: "+1 (852) 565-3727",
        company: "ZBOO",
        email: "masonbarry@zboo.com",
    },
    {
        id: "6891dafc1824fd73c61a3e8c",
        firstName: "Stafford",
        lastName: "Robinson",
        gender: "male",
        phone: "+1 (989) 401-2368",
        company: "ECRAZE",
        email: "staffordrobinson@ecraze.com",
    },
    {
        id: "6891dafc1f8a53906b16d8af",
        firstName: "Harrington",
        lastName: "Day",
        gender: "male",
        phone: "+1 (914) 589-2774",
        company: "VIRXO",
        email: "harringtonday@virxo.com",
    },
    {
        id: "6891dafc5511ab73acceec31",
        firstName: "Beulah",
        lastName: "Farmer",
        gender: "female",
        phone: "+1 (866) 518-3075",
        company: "SLAX",
        email: "beulahfarmer@slax.com",
    },
    {
        id: "6891dafcc10ec2e4e00ba78a",
        firstName: "Martinez",
        lastName: "Garner",
        gender: "male",
        phone: "+1 (895) 591-3430",
        company: "VALREDA",
        email: "martinezgarner@valreda.com",
    },
    {
        id: "6891dafc8403963f0b03fbb1",
        firstName: "Francine",
        lastName: "Byers",
        gender: "female",
        phone: "+1 (985) 413-3471",
        company: "BLURRYBUS",
        email: "francinebyers@blurrybus.com",
    },
    {
        id: "6891dafca07ef4892db9c79a",
        firstName: "Cooley",
        lastName: "Franklin",
        gender: "male",
        phone: "+1 (891) 423-3224",
        company: "DOGSPA",
        email: "cooleyfranklin@dogspa.com",
    },
    {
        id: "6891dafcaf1b20c283ea56af",
        firstName: "Padilla",
        lastName: "Stein",
        gender: "male",
        phone: "+1 (839) 555-3919",
        company: "FRENEX",
        email: "padillastein@frenex.com",
    },
    {
        id: "6891dafc2ff55ba0e0d88362",
        firstName: "Bolton",
        lastName: "Rivera",
        gender: "male",
        phone: "+1 (960) 413-3248",
        company: "TALAE",
        email: "boltonrivera@talae.com",
    },
    {
        id: "6891dafc266362f0a1cd14ab",
        firstName: "Goodman",
        lastName: "Vasquez",
        gender: "male",
        phone: "+1 (938) 505-3840",
        company: "QUOTEZART",
        email: "goodmanvasquez@quotezart.com",
    },
    {
        id: "6891dafcf946572902e0c7ba",
        firstName: "Gibbs",
        lastName: "Heath",
        gender: "male",
        phone: "+1 (891) 411-3554",
        company: "QUARMONY",
        email: "gibbsheath@quarmony.com",
    },
];

function App() {
    return (
        <section>
            <UsersGrid users={USERS} />
        </section>
    );
}

export default App;
